use chrono::Utc;
use color_eyre::eyre::{eyre, Context, Result};
use std::fs;
use std::path::{Path, PathBuf};

const GENERATED_MARKER: &str = "Generated by cargo xtask lint --install-hooks";
const HOOK_CONTENT: &str = r#"#!/bin/sh
set -eu
# Generated by cargo xtask lint --install-hooks
git diff --cached --name-only --diff-filter=ACM | grep -q '\.rs$' || exit 0
exec cargo xtask lint --staged-only
"#;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum HookState {
    Absent,
    Generated,
    Foreign,
}

fn classify_hook(content: Option<&str>) -> HookState {
    match content {
        None => HookState::Absent,
        Some(value) if value.contains(GENERATED_MARKER) => HookState::Generated,
        Some(_) => HookState::Foreign,
    }
}

fn repository_root() -> Result<PathBuf> {
    let output = std::process::Command::new("git")
        .args(["rev-parse", "--show-toplevel"])
        .output()
        .context("failed to locate the repository root")?;
    if !output.status.success() {
        return Err(eyre!("not a git repository"));
    }
    Ok(PathBuf::from(
        String::from_utf8_lossy(&output.stdout).trim(),
    ))
}

fn hook_path() -> Result<PathBuf> {
    Ok(repository_root()?.join(".git/hooks/pre-commit"))
}

fn read_hook(path: &Path) -> Result<Option<String>> {
    match fs::read_to_string(path) {
        Ok(content) => Ok(Some(content)),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(error) => Err(error.into()),
    }
}

pub fn install_hooks() -> Result<()> {
    let path = hook_path()?;
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    if classify_hook(read_hook(&path)?.as_deref()) == HookState::Foreign {
        let backup = path.with_file_name(format!(
            "pre-commit.backup.{}",
            Utc::now().format("%Y%m%d%H%M%S")
        ));
        fs::rename(&path, backup).context("failed to back up the existing pre-commit hook")?;
    }
    fs::write(&path, HOOK_CONTENT).context("failed to write the generated pre-commit hook")?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut permissions = fs::metadata(&path)?.permissions();
        permissions.set_mode(0o755);
        fs::set_permissions(&path, permissions)?;
    }
    println!("Installed generated pre-commit hook at {}", path.display());
    Ok(())
}

pub fn uninstall_hooks() -> Result<()> {
    let path = hook_path()?;
    match classify_hook(read_hook(&path)?.as_deref()) {
        HookState::Absent => println!("No generated pre-commit hook is installed."),
        HookState::Generated => {
            fs::remove_file(&path).context("failed to remove the generated pre-commit hook")?;
            println!("Removed generated pre-commit hook.");
        }
        HookState::Foreign => {
            return Err(eyre!(
                "pre-commit hook is foreign; refusing to remove {}",
                path.display()
            ));
        }
    }
    Ok(())
}

pub fn show_status() -> Result<()> {
    let path = hook_path()?;
    let state = classify_hook(read_hook(&path)?.as_deref());
    let label = match state {
        HookState::Absent => "absent",
        HookState::Generated => "generated",
        HookState::Foreign => "foreign",
    };
    println!("pre-commit hook: {label}");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn classifies_absent_generated_and_foreign_hooks() {
        assert_eq!(classify_hook(None), HookState::Absent);
        assert_eq!(
            classify_hook(Some(
                "#!/bin/sh\nGenerated by cargo xtask lint --install-hooks\n"
            )),
            HookState::Generated
        );
        assert_eq!(
            classify_hook(Some("#!/bin/sh\necho custom\n")),
            HookState::Foreign
        );
    }

    #[test]
    fn only_generated_content_is_removable() {
        assert_eq!(classify_hook(Some(HOOK_CONTENT)), HookState::Generated);
        assert_ne!(classify_hook(Some("custom hook")), HookState::Generated);
        assert_ne!(classify_hook(None), HookState::Generated);
    }
}
